### ISSUE TITLE
语法出错

### ISSUE THREAD

**Issue by xusenlin** [overnote/golang#6]
您好，非常感谢提供这么好的笔记。在学习过程中发现笔记里面的代码片段报错，看似合理的写法却编译不通过。

位置：
02-GO语法 里的 4.5 关键字iota 中的：
```
const (
    g = iota    	        //0
    h,i,j = iota,iota,iota 	       
    k 				        // 2
)
```

这里的k出错了，但是没有h,i,j = iota,iota,iota 这一行的话就没有问题。

**Comment by ruyuejun** [comment]
谢谢@xusenlin
修正如下：
将k注释掉了(这里为了展示h,i,j 在同行使用 iota 不递增效果)，并添加了不能再次定义常量的说明

**Comment by xusenlin** [comment]
嗯嗯，下面只是不能定义缺省值的常量，但是 继续定义k = iota 和 k = "abc" 这些常量仍然可以，对于这种问题不知道有没有官方说明。

**Comment by ruyuejun** [comment]
厉害啦，准备修正
